egovernments/frontend

- web/rainmaker/dev-packages/egov-tradelicence-dev/src/ui-config/screens/specs/utils/receiptPdf.js
- web/rainmaker/dev-packages/egov-ui-kit-dev/src/common/propertyTax/PaymentStatus/Components/acknowledgementFormPDF.js
> bug fixes localisation

- web/rainmaker/dev-packages/egov-tradelicence-dev/src/ui-config/screens/specs/utils/receiptPdf.js
- web/rainmaker/dev-packages/egov-ui-kit-dev/src/common/propertyTax/PaymentStatus/Components/acknowledgementFormPDF.js
> Localisation changes 9th dec

- web/rainmaker/dev-packages/egov-tradelicence-dev/src/ui-config/screens/specs/tradelicence/payResource/payment-methods.js
Remove IFSC from payment mode DD in TL PI-6836
> Remove IFSC from payment mode DD in TL PI-6836

- web/rainmaker/dev-packages/egov-tradelicence-dev/src/ui-config/screens/specs/tradelicence/applyResource/footer.js
- web/rainmaker/dev-packages/egov-ui-framework-core/src/ui-molecules/MenuButton/index.js
- web/rainmaker/dev-packages/egov-ui-framework-core/src/ui-molecules/index.js
- web/rainmaker/dev-packages/egov-ui-kit-dev/src/custom-icons/filter.js
- web/rainmaker/dev-packages/egov-workflow-dev/src/ui-containers-local/WorkFlowContainer/index.js
- web/rainmaker/dev-packages/egov-workflow-dev/src/ui-molecules-local/Footer/index.js
- web/rainmaker/dev-packages/egov-workflow-dev/src/ui-molecules-local/MenuButton/index.js
- web/rainmaker/packages/citizen/src/modules/App.js
- web/rainmaker/packages/employee/src/modules/employee/Inbox/components/FilterDialog/index.js
- web/rainmaker/packages/employee/src/modules/employee/Inbox/components/FilterDialog/index.scss
- web/rainmaker/packages/employee/src/modules/employee/Inbox/components/Table/index.js
- web/rainmaker/packages/employee/src/modules/employee/Inbox/components/Table/index.scss
- web/rainmaker/packages/employee/src/modules/employee/Inbox/components/TableData/index.js
- web/rainmaker/packages/employee/src/modules/employee/Inbox/components/actionItems.js
- web/rainmaker/packages/employee/src/modules/employee/Inbox/index.js
* Workflow-2.0 changes
* WF changes
* Fixed Inbox
* Added moduleClick functionality
* integrated Quick actions with action call
* Update index.js
* Deleted yarn lock and lerna_Backup
> Workflow2.0 (#113)

- web/rainmaker/dev-packages/egov-tradelicence-dev/src/ui-config/screens/specs/tradelicence/search.js
- web/rainmaker/dev-packages/egov-ui-kit-dev/src/common/common/Header/components/UserSettings/index.js
- web/rainmaker/dev-packages/egov-ui-kit-dev/src/common/common/Header/index.js
https://digit-discuss.atlassian.net/browse/RDS-15
> Localization bug while change of language fix RDS-15

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-atoms-local/Checkbox/index.scss
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-atoms-local/Icons/index.scss
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/utils/index.scss
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns-citizen/myConnectionDetails/myConnectionDetails.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns-citizen/searchResource/functions.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns-citizen/searchResource/searchResults.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/index.scss
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/connection-details.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/meter-reading.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/meterReading/index.scss
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/meterReading/meterReadingEditable.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/searchResource/functions.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/searchResource/searchResults.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/viewBill.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-containers-local/CheckboxContainer/index.scss
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-containers-local/DownloadFileContainer/index.scss
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-molecules-local/MyConnections/index.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-molecules-local/RadioGroup/index.scss
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-utils/commons.js
- Changes in meter Reading
- Changes in view Bill
- Changes in connection details
- Changes in Search Results for water and sewerage
> Code update with the latest ui changes in wns

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns-citizen/searchResource/searchResults.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/connectionDetailsResource/service-details.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-molecules-local/MyConnections/index.js
This is to fix the route error that we are getting on routing employee module screens from citizen
> Router error on dev fix

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/acknowledgementResource/footers.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/apply.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/basicDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/boundarydetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/scrutinyDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/searchResource/bpaApplication.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/searchResource/citizenFooter.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/searchResource/functions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/searchResource/searchResults.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/basicSummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/plotAndBoundaryInfoSummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/scrutinySummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/receiptTransformer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
- web/rainmaker/dev-packages/egov-ui-framework-core/src/ui-utils/commons.js
- web/rainmaker/dev-packages/egov-workflow-dev/src/ui-containers-local/WorkFlowContainer/index.js
- web/rainmaker/dev-packages/egov-workflow-dev/src/ui-molecules-local/ActionDialog/index.js
- web/rainmaker/dev-packages/egov-workflow-dev/src/ui-molecules-local/Footer/index.js
BPA Application Workflow changes, code clean up and bug fixes.
Please note, we had to change workflow container component logic for BPA purpose.
> BPA Application Workflow changes

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
BPA application bug fix. Please also deployee on dev and do not delete bpa-phase-1b.
> BPA application bug fix

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/searchResource/functions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/searchResource/searchResults.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-containers-local/BpaEstimateCardContainer/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-containers-local/DocumentListContainer/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-molecules-local/MeterReading/index.js
Overriding file changes reg Sudhanshu instructions
> Overriding file changes reg Sudhanshu instructions

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/edcrscrutiny/functions.js
This reverts commit 2f9178bf9ac7a28c6da5d84159a467603270a2c3.
> Revert "Bpaedcr newsprint (#219)"

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/edcrscrutiny/functions.js
Reverts egovernments/frontend#221
> Revert "Bpaedcr newsprint"

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/acknowledgement.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/acknowledgementResource/footers.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/apply.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/basicDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/boundarydetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/propertyLocationDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/scrutinyDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/citizen-pay.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/payResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/basicSummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/plotAndBoundaryInfoSummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/scrutinySummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/generatePdfForBpa.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/receiptTrasformerForBpa.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-containers-local/BpaPaymentRedirectPage/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/api.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
> Fixed the Known Issues

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/searchResource/functions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/api.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
- web/rainmaker/dev-packages/egov-workflow-dev/src/ui-containers-local/WorkFlowContainer/index.js
> BPA Work flow changes

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
Changed the collection url in bpa
> Changed the collection url in bpa

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/api.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
- web/rainmaker/dev-packages/egov-workflow-dev/src/ui-containers-local/WorkFlowContainer/index.js
- web/rainmaker/dev-packages/egov-workflow-dev/src/ui-molecules-local/Footer/index.js
Workflow changes for BPA Citizen
> Bpa phase 1b

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/api.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
- web/rainmaker/dev-packages/egov-workflow-dev/src/ui-containers-local/WorkFlowContainer/index.js
- web/rainmaker/dev-packages/egov-workflow-dev/src/ui-molecules-local/Footer/index.js
Workflow changes for bpa citizen
> Workflow changes for bpa citizen

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/api.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
- web/rainmaker/dev-packages/egov-workflow-dev/src/ui-containers-local/WorkFlowContainer/index.js
- web/rainmaker/dev-packages/egov-workflow-dev/src/ui-molecules-local/Footer/index.js
Work Related changes for BPA.
Note : Dont delete this branch.
> Work Related changes for BPA

- web/rainmaker/dev-packages/egov-tradelicence-dev/src/ui-config/screens/specs/tradelicence/applyResource/footer.js
- web/rainmaker/dev-packages/egov-tradelicence-dev/src/ui-config/screens/specs/tradelicence/searchResource/searchResults.js
on sendback citizen wasn't able to download  application. Fix is done
> RAIN-338 fix

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/acknowledgement.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/applicantDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
> NOC Documents Issue Fixed

- web/rainmaker/dev-packages/egov-ui-framework-core/src/ui-config/screens/specs/utils/receiptPdf.js
Remove (Citizen Copy) from Receipt PI-2192
> Remove (Citizen Copy) from Receipt PI-2192

- web/rainmaker/dev-packages/egov-tradelicence-dev/src/ui-config/screens/specs/utils/receiptPdf.js
> Change TL Format PI-5571

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-atoms-local/MenuListCompositionForBpa/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-atoms-local/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder-citizen/citizenSearchResource/citizenFunctions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder-citizen/my-applications.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/acknowledgement.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/acknowledgementResource/footers.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/index.scss
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/nocVerificationDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/applicantSummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/basicSummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/plotAndBoundaryInfoSummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/scrutinySummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-containers-local/NocListContainer/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/MapLocator/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/NocList/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/api.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
- web/rainmaker/dev-packages/egov-ui-framework-core/src/ui-molecules/SingleApplication/index.js
> BPA Issues fixed

- web/rainmaker/dev-packages/egov-ui-kit-dev/src/redux/app/actions.js
rainmaker-bpa added in the localization url
> rainmaker-bpa added in the localization url

- web/rainmaker/dev-packages/egov-tradelicence-dev/src/ui-config/screens/specs/tradelicence/applyResource/tradeDetails.js
Update default Accessories count 1 PI-5599
> Default Accessories count 1 PI-5599

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/apply.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/propertyLocationDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/scrutinyDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/scrutinySummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/NocList/index.js
- web/rainmaker/dev-packages/egov-workflow-dev/src/ui-containers-local/TaskStatusContainer/index.js
- web/rainmaker/dev-packages/egov-workflow-dev/src/ui-containers-local/WorkFlowContainer/index.js
- web/rainmaker/dev-packages/egov-workflow-dev/src/ui-molecules-local/Footer/index.js
Workflow history and localization for mohalla changes
> Workflow history and localization for mohalla changes

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/scrutinyDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/scrutinySummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
residential and sub occupancy fixed
> residential and sub occupancy fixed

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/acknowledgement.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/apply.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/index.scss
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/propertyLocationDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/citizen-pay.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/payResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/documentsSummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/nocSummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/scrutinySummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-containers-local/BpaDocumentListContainer/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-containers-local/BpaPaymentRedirectPage/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/BpaDocumentList/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/MapLocator/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/NocList/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
- web/rainmaker/dev-packages/egov-common-dev/src/ui-config/screens/specs/egov-common/payResource/footer.js
- web/rainmaker/dev-packages/egov-ui-framework-core/src/ui-molecules/SingleApplication/index.js
> Documents issues fixed.

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/apply.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/applicantDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search-preview.js
Download button, DOB and GIS coordinates issues fixed.
> Download button, DOB and GIS coordinates issues fixed.

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/apply.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/basicDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/boundarydetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/index.scss
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/basicSummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
> Owers Issue fixed.

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/apply.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/applicantDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/basicDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/boundarydetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/propertyLocationDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/scrutinyDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.css
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
> Unwanted styles removed.

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/applicantDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/applicantSummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/scrutinySummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.css
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
> Apply issues fixed.

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/basicDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/boundarydetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
> Bpa alignmentissues fixed.

- web/rainmaker/dev-packages/egov-ui-kit-dev/src/common/propertyTax/PaymentStatus/Components/receiptsPDF.js
Change online payment link style in pt receipt. which is write under notes
> Change online payment link style in pt receipt.

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/applicantDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-containers-local/BpaCheckboxContainer/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-containers-local/BpaCheckboxContainer/index.scss
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-containers-local/index.js
> Bpa primary owner issue fixed

- web/rainmaker/dev-packages/egov-tradelicence-dev/src/ui-config/screens/specs/tradelicence/applyResource/adhocPopup.js
Update total amount after 100% rebate PI-6947
> Update total amount after 100% rebate PI-6947

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/scrutinyDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/scrutinySummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.css
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
> Bpa occupancy issues fixed.

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/edcrscrutiny/acknowledgementResource/index.css
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/acknowledgementResource/footers.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-common-dev/src/ui-config/screens/specs/egov-common/pay.js
- web/rainmaker/dev-packages/egov-common-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-workflow-dev/src/ui-containers-local/WorkFlowContainer/index.js
> Bpa payment issues fixed.

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/acknowledgement.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/searchResource/citizenFooter.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/BpaDocumentList/index.js
- web/rainmaker/dev-packages/egov-workflow-dev/src/ui-containers-local/WorkFlowContainer/index.js
> Bpa fd issues fixed.

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/searchResource/functions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/NocList/index.js
> edcr issue fixed

- build/build-config.yml
build-config.yml- added builds/ in job config name
> Update build-config.yml (#408)

- web/rainmaker/dev-packages/egov-hrms-dev/src/ui-config/screens/specs/hrms/searchResource/searchForm.js
Search Employee by Mobile No in HRMS PI-7119
> Search Employee by Mobile No in HRMS PI-7119

- web/rainmaker/dev-packages/egov-tradelicence-dev/src/ui-config/screens/specs/tradelicence/applyResource/adhocPopup.js
- web/rainmaker/dev-packages/egov-tradelicence-dev/src/ui-config/screens/specs/utils/receiptPdf.js
- web/rainmaker/dev-packages/egov-tradelicence-dev/src/ui-config/screens/specs/utils/receiptTransformer.js
Penalty/Rebate reason and comments show on receipt PI-6854
> Add Penalty/Rebate reason and comments  PI-6854

- web/rainmaker/packages/employee/src/modules/employee/Inbox/components/TableData/index.scss
> Search Icon fix

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/acknowledgement.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/acknowledgementResource/footers.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/apply.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/applicantDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/boundarydetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/propertyLocationDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/searchResource/citizenFooter.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/applicantSummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/basicSummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/documentsSummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/scrutinySummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
- web/rainmaker/dev-packages/egov-ui-framework-core/src/ui-molecules/ComponentInterface/index.js
- web/rainmaker/dev-packages/egov-ui-framework-core/src/ui-molecules/ComponentInterface/moduleConfig.js
* counter payment and citizen workflow
* citizen workflow changes
* OAP-187,188,189
* changes in the citizen footer
* added bpa in framework for buttons
* changes in the applicant details.
* missing file added
> Bpa counter payment (#479)

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summary.js
> fixed issue.

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/apply.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/applicantDetails.js
- web/rainmaker/dev-packages/egov-ui-framework-core/src/ui-molecules/SingleApplication/index.js
> added intiated state for BPA

- web/rainmaker/dev-packages/egov-uc-dev/src/ui-config/screens/specs/utils/recieptPdf.js
Change G8 to Manual G8 PI-7225
> Change G8 to Manual G8 PI-7225

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder-citizen/citizenSearchResource/citizenFunctions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/edcrscrutiny/acknowledgementResource/gotoHomeFooter.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/searchResource/functions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
OAP-169:My Application to show New construction application first, OAP-159:Validation message - Invalid input is shown even before entering any value, OAP-205:edcr - Go to Home button is redirecting to a blank screen
> OAP159169205

- web/rainmaker/dev-packages/egov-tradelicence-dev/src/ui-config/screens/specs/utils/receiptPdf.js
- web/rainmaker/dev-packages/egov-ui-framework-core/src/ui-config/screens/specs/utils/receiptPdf.js
> Update TL Receipt PI-7219

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder/applyResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/fieldSummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/fieldinspectionSummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-containers-local/CheckListContainer/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-containers-local/FeildInspectionCards/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-containers-local/FieldInspectionContainer/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-containers-local/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/CheckList/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
Bpa FieldInpection development.
> Bpa FieldInpection development

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
> Removed Unwanted Code.

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder/applyResource/licenseeDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/apply.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/basicDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/scrutinySummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
> BPA and Stackholder issues.

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-atoms-local/MenuButton/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/edcrscrutiny/acknowledgementResource/acknowledgementUtils.js
Print/download button issue fixed.
> Print/download button issue fixed.

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-atoms-local/MenuButton/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/edcrscrutiny/acknowledgementResource/acknowledgementUtils.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-containers-local/EstimateCardContainer/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/FeesEstimateCard/index.js
Stakeholder fee description issue fixed.
> Stakeholder fee description issue fixed.

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/searchResource/citizenFooter.js
Citizen approval and send to architect button issue.
> Citizen approval and send to architect button issue.

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder/searchResource/functions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/searchResource/citizenFooter.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
- web/rainmaker/dev-packages/egov-ui-framework-core/src/ui-molecules/SingleApplication/index.js
citizen footer with submit button fixed.
> citizen footer with submit button fixed.

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder/applyResource/licenseeDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
> stack holder changes done.

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/searchResource/citizenFooter.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/ActionDialog/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/ActionDialog/index.scss
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/index.js
send To citizen and approval popup for remarks done.
> send To citizen and approval popup for remarks done.

- web/rainmaker/dev-packages/egov-ui-framework-core/src/ui-molecules/SingleApplication/index.js
> added break for bpa url

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder/applyResource/licenseeDetails.js
- web/rainmaker/dev-packages/egov-ui-framework-core/src/ui-molecules/SingleApplication/index.js
> issue fixed.

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/search-preview.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-molecules-local/Applications/index.js
- web/rainmaker/dev-packages/egov-workflow-dev/src/ui-containers-local/WorkFlowContainer/index.js
> Citizen task details routing is done. citizen workflow integration is done

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/apply.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/propertyLocationDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/api.js
- web/rainmaker/dev-packages/egov-ui-kit-dev/src/redux/app/actions.js
localization, mohalla and mdms search fixed.
> localization, mohalla and mdms search fixed.

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/edcrscrutiny/functions.js
> edcr URl is changed.

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/edcrscrutiny/functions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/api.js
edcr urls change in edcr and bpa
> edcr urls change in edcr and bpa

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/edcrscrutiny/functions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/api.js
> edcr change

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search-preview.js
> Permit order displying issue.

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder/applyResource/declarationDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder/applyResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder/applyResource/licenseeDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder/applyResource/tradeReviewDetails.js
oap248 bpa stackholder declaration.
> oap248 bpa stackholder declaration.

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/searchResource/citizenFooter.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/declarationSummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
bpa declarations for citizen and stakeholder done.
> bpa declarations for citizen and stakeholder done.

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-atoms-local/PermitListCondition/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-atoms-local/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/fieldSummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/permitConditions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/permitListSummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-containers-local/BpaConditionsContainer/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-containers-local/index.js
> bpa-conditions list done.

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder-citizen/citizenSearchResource/citizenFunctions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/acknowledgementResource/footers.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/searchResource/citizenFooter.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-ui-framework-core/src/ui-molecules/ComponentInterface/index.js
- web/rainmaker/dev-packages/egov-ui-framework-core/src/ui-molecules/ComponentInterface/moduleConfig.js
- web/rainmaker/dev-packages/egov-ui-framework-core/src/ui-molecules/SingleApplication/index.js
- web/rainmaker/dev-packages/egov-workflow-dev/src/ui-containers-local/WorkFlowContainer/index.js
> Bpa low risk wf

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/apply.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-workflow-dev/src/ui-containers-local/WorkFlowContainer/index.js
hiding the citizen footer in workflow
> hiding the citizen footer in workflow

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
> Citizen footer enabled

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder/acknowledgementResource/applicationSuccessFooter.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder/applyResource/footer.js
stakeholder payment issue fixed
> billing service expecting businessService as mandatory.

- web/rainmaker/dev-packages/egov-tradelicence-dev/src/ui-config/screens/specs/utils/receiptPdf.js
- web/rainmaker/dev-packages/egov-ui-framework-core/src/ui-config/screens/specs/utils/receiptPdf.js
Replace Owner Name to Trade Owner Name PI-7261
> Replace Owner Name to Trade Owner Name PI-7261

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder-citizen/citizenSearchResource/citizenFunctions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/apply.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/scrutinyDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
> bpa licencetype added.

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/scrutinyDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
removed unwanted fields in bpa
> removed unwanted fields in bpa

- web/rainmaker/dev-packages/egov-workflow-dev/src/ui-molecules-local/ActionDialog/index.js
[PI-6909] made Assignee Name mandatory
> [PI-6909] made Assignee Name mandatory

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/scrutinyDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/scrutinySummary.js
removed fields in BPA product.
> removed fields in BPA product.

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/footer.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-utils/commons.js
- Added the if condition to check if the application has documents, before going to the next step.
- Previous step to start from top.
> Fix for error on initiated and not submitted application

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder/applyResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder/applyResource/licenseeDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/DocumentList/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
> bihar changes merging.

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/acknowledgement.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/declarationSummary.js
- web/rainmaker/dev-packages/egov-ui-framework-core/src/ui-molecules/SingleApplication/index.js
- web/rainmaker/dev-packages/egov-workflow-dev/src/ui-containers-local/WorkFlowContainer/index.js
revocation condition added in WF
> revocation condition added in WF

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/acknowledgement.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/acknowledgementResource/applicationSuccessFooter.js
- Verified all the downloads were working in both task details and acknowledgement.
- Verified print at both task details and acknowledgement.
- Covered for water, sewerage and water and sewerage.
> Fix code changes on download

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/apply.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/documentDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/fieldinspectionSummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-containers-local/DownloadFileContainer/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/BpaDocumentList/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/MultiDownloadCard/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/NocList/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/UploadMultipleFile/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/UploadSingleFile/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
> Bpa final multiple docs

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/acknowledgement.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/apply.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/additionalDetails.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/review-trade.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/reviewConnectionDetails.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/search-preview.js
- Added the code review changes
- Verified and tested in UI for one complete create and edit flow.
> Code review changes added

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/apply.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/documentDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/fieldinspectionSummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-containers-local/DownloadFileContainer/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/BpaDocumentList/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/MultiDownloadCard/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/NocList/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/UploadMultipleFile/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
> Bpa multiple documents

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
> erros resolved.

- web/rainmaker/dev-packages/egov-ui-framework-core/src/ui-atoms/CountdownTimer/index.js
- web/rainmaker/dev-packages/egov-ui-framework-core/src/ui-atoms/CountdownTimer/index.scss
- web/rainmaker/dev-packages/egov-ui-framework-core/src/ui-atoms/index.js
- web/rainmaker/dev-packages/egov-ui-kit-dev/src/redux/auth/actions.js
- web/rainmaker/packages/citizen/src/modules/citizen/User/OTP/components/OTPForm/index.js
- web/rainmaker/packages/citizen/src/modules/citizen/User/OTP/index.js
mseva-OTP
60s period will come for subsequent attempts
unised code removed
> Timer added on OTP Page

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder/applyResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/edcrscrutiny/apply.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/searchResource/citizenFooter.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/ActionDialog/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
stakeHolder Update Documents issue fixed.
> stakeHolder Update Documents issue fixed.

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder-citizen/citizenSearchResource/citizenFunctions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder-citizen/my-applications.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/apply.js
- web/rainmaker/dev-packages/egov-ui-framework-core/src/ui-molecules/SingleApplication/index.js
Citizen getting application edit option and valid up to date in my applications fixed.
> Citizen getting application edit option and valid up to date in my applications fixed.

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-atoms-local/NoteAtom/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-atoms-local/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder/applyResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder/applyResource/tradeReviewDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/searchResource/functions.js
> stakeholder footnote added.

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/BpaDocumentList/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/CheckList/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/DocumentList/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/NocList/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
> Document UI issues

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/apply.js
changes for citizen comments in apply.
> changes for citizen comments in apply.

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-containers-local/DownloadFileContainer/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/BpaDocumentList/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/MultiDownloadCard/index.js
documents details issues in bpa.
> documents details issues in bpa.

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
> bpareg documents id changes

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/footer.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/functions.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/ownerDetails.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-utils/commons.js
- Tested the error messages, Worked fine in local
- Also added NA fix for few property fields.
> Error message fix in apply

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-utils/commons.js
- In previous commit, It had the return statement in loop, so it would never take second iteration.
- This issue has been fix in this commit.
> bug fix in owner validation, removed return from loop.

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/acknowledgement.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/searchResource/citizenFooter.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/ActionDialog/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/BpaDocumentList/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
send back to citizen ui changes.
> send back to citizen ui changes.

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/apply.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/ActionDialog/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
urls changes in bpa application.
> urls changes in bpa application.

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
> document condition added

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/searchResource/functions.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/searchResource/searchApplicationResults.js
- NA was coming as link in search, fixed.
- Application status fix, removed underscore while displaying.
> Application status fix, also NA was coming as link

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder-citizen/citizenSearchResource/citizenFunctions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder-citizen/my-applications.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder/applyResource/review-license.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder/applyResource/tradeReviewDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/apply.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/declarationSummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.css
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
> Done with OAP-270 and OAP-272

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/edcrscrutiny/acknowledgement.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/edcrscrutiny/functions.js
edcr abort case handling is done
> edcr abort case handling is done

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/edcrscrutiny/functions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/api.js
- web/rainmaker/packages/citizen/.env
> edcr new url updated

- web/rainmaker/dev-packages/egov-ui-kit-dev/src/common/common/DocumentList/index.js
- web/rainmaker/dev-packages/egov-ui-kit-dev/src/common/common/DocumentListContainer/index.js
- web/rainmaker/dev-packages/egov-ui-kit-dev/src/common/propertyTax/PTAcknowledgement/index.js
- web/rainmaker/dev-packages/egov-ui-kit-dev/src/common/propertyTax/Property/components/TotalDues/index.js
https://digit-discuss.atlassian.net/browse/RAIN-861
> Fix for adding Business Service in Fetchbill

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-atoms-local/AutoSuggest/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/apply.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/index.scss
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/scrutinyDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/scrutinySummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.css
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-containers-local/AutosuggestContainer/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/Table/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
> added multiple blocks in BPA 

- web/rainmaker/packages/citizen/package.json
- web/rainmaker/packages/employee/package.json
trying to fix build issues as per murali suggestion.
> trying to fix build issues as per murali suggestion.

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/acknowledgement.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/functions.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-utils/commons.js
- Added the fix WOR-203
- Added the fix for WOR-206
> Added the fix for WOR-203 and WOR-206

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
> sub occupancy id fixed.

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-containers-local/DownloadFileContainer/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/BpaDocumentList/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/MultiDownloadCard/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
> oap-319 and 323

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/scrutinyDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.css
> bpa occupancy alignment issue

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-containers-local/DownloadFileContainer/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/BpaDocumentList/index.js
architect added to send back docs
> architect added to send back docs

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/fieldSummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/fieldinspectionSummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.css
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-containers-local/DownloadFileContainerForFI/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-containers-local/DownloadFileContainerForFI/index.scss
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-containers-local/FieldInspectionContainer/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-containers-local/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/CheckList/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/MultiDownloadCard/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/NocList/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/UploadMultipleFile/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/index.js
multiple fi feature added in bpa
> multiple fi feature added in bpa

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/index.scss
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/scrutinyDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search-preview.js
> bpa issues fixed in citizen

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/scrutinyDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/scrutinySummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
removed unwanted fields in scrutiny details
> removed unwanted fields in scrutiny details

- web/rainmaker/dev-packages/egov-ui-kit-dev/src/utils/commons.js
module name added for localization
> module name added for localization

- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-common-screens/applyResource/footer.js
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-common-screens/applyResourceMutation/propertyAssemblyDetails.js
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-common-screens/applyResourceMutation/propertyLocationDetails.js
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-common-screens/applyResourceMutation/propertyOwnershipDetails.js
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-common-screens/register-property.js
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-containers-local/CheckboxContainerPTCommon/index.js
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-containers-local/CheckboxContainerPTCommon/index.scss
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-containers-local/index.js
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-utils/commons.js
- The count of file is more due to create api, required changes in multiple files.
- The checkbox has been added as well, so for that I had to create a new container, didn't want to disturb the existing one so.
> Added fix create API call, added checkbox in register property

- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-common-screens/applyResource/footer.js
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-common-screens/register-property.js
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-containers-local/SuccessPTPopupContainer/index.js
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-containers-local/index.js
> Added Popup functionality

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-utils/commons.js
TenantId should be used from Property, so that W&S apply connection searches properly after calling Create/Update API.
> WOR-234 W&S Create Issue fix

- .gitignore
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-atoms-local/UploadedDocument/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-atoms-local/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder-citizen/citizenSearchResource/citizenFunctions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/apply.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/applyDocSummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/declarationSummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/previewSummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.css
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-containers-local/BpaCheckboxContainer/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-containers-local/DocumentSummaryContainer/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-containers-local/DocumentSummaryContainer/index.scss
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-containers-local/PreviewContainer/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-containers-local/PreviewContainer/index.scss
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-containers-local/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/BpaDocumentList/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/BpaDocumentList/index.scss
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/BpaFeesEstimateCard/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/MultiDocDetailCard/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/SingleDocDetailCard/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/UploadCard/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/UploadMultipleFile/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/UploadMultipleFile/index.scss
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/index.js
- web/rainmaker/package.json
This Pull request contains the changes related to BPA documents. 
Please review
> Bpa arch changes

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder-citizen/citizenSearchResource/citizenFunctions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder-citizen/home.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder-citizen/my-applications-stakeholder.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder/searchResource/functions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/searchResource/functions.js
> Bpa stake holder changes

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/apply.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/MultiDocDetailCard/index.js
This PR includes changes related to disabling the drop-down asking architect to choose the licenseType if he/she has multiple license Types
> #OAP-364 Changes related to disabling licenceType selection

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder-citizen/citizenSearchResource/citizenFunctions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder-citizen/my-applications-stakeholder.js
issues fixed in stakeholder view
> issues fixed in stakeholder view

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder/applyResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder/searchResource/functions.js
This PR includes changes related to tenantId
> OAP-367 TenantId changes

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder-citizen/my-applications-stakeholder.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder/searchResource/functions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder/searchResource/searchResults.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/searchResource/functions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/searchResource/searchResults.js
table data mapping updated according to framework
> table data mapping updated according to framework

- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/abg/billSearchResources/function.js
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/abg/billSearchResources/searchResults.js
- web/rainmaker/dev-packages/egov-noc-dev/src/ui-config/screens/specs/fire-noc/searchResource/functions.js
- web/rainmaker/dev-packages/egov-noc-dev/src/ui-config/screens/specs/fire-noc/searchResource/searchResults.js
- web/rainmaker/dev-packages/egov-tradelicence-dev/src/ui-config/screens/specs/tradelicence/searchResource/functions.js
- web/rainmaker/dev-packages/egov-tradelicence-dev/src/ui-config/screens/specs/tradelicence/searchResource/searchResults.js
- web/rainmaker/dev-packages/egov-uc-dev/src/ui-config/screens/specs/uc/universalCollectionResources/function.js
- web/rainmaker/dev-packages/egov-uc-dev/src/ui-config/screens/specs/uc/universalCollectionResources/searchResults.js
Localization implementation in Table configurations in UI for below modules -
egov-abg-dev
egov-noc-dev
egov-tradelicence-dev
gov-uc-dev
> RAIN-970  - Added Localization implementation in Table

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder-citizen/my-applications-stakeholder.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
missing title added in stakeholder
> missing title added in stakeholder

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder/searchResource/functions.js
This PR includes the changes related to exclusion of city name from tenantId
> Committing the changes related to city name in tenanid in searchapi

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/fieldSummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/fieldinspectionSummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/MultiDocDetailCard/index.js
added localization for missing
> added localization for missing

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder/applyResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder/searchResource/functions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
This PR contains changes related to tenentID to be merged to R2
> Changes related to tenanit in Relese2020_v2

- web/rainmaker/dev-packages/pt-citizen-dev/src/Screens/FormWizard/index.js
PI-7525 Enable Zirakpur citizen online assessment
> PI-7525 Enable Zirakpur citizen online assessment

- web/rainmaker/dev-packages/egov-uc-dev/src/ui-config/screens/specs/uc/universalCollectionResources/function.js
https://digit-discuss.atlassian.net/browse/RAIN-983
> UC Reset Issue Fixed

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/acknowledgementResource/footers.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/ActionDialog/index.js
- web/rainmaker/dev-packages/egov-workflow-dev/src/ui-containers-local/WorkFlowContainer/index.js
> changes done for coments

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-atoms-local/UploadedDocument/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-containers-local/PreviewContainer/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/BpaDocumentList/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/MultiDocDetailCard/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/SingleDocDetailCard/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
This PR contains changes related to all document issues
> Document Changes

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder-citizen/my-applications-stakeholder.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/edcrscrutiny/functions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/searchResource/bpaApplication.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/acknowledgement.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/apply.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/applyResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/applyResource/index.scss
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/applyResource/scrutinyDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/searchResource/citizenFooter.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/summary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/summaryResource/documentAndNocSummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/summaryResource/scrutinySummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/BpaDocumentList/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
- web/rainmaker/dev-packages/egov-ui-framework-core/src/ui-molecules/ComponentInterface/index.js
- web/rainmaker/dev-packages/egov-ui-framework-core/src/ui-molecules/ComponentInterface/moduleConfig.js
- web/rainmaker/dev-packages/egov-workflow-dev/src/ui-containers-local/WorkFlowContainer/index.js
> OC New changes

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/searchResource/functions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/searchResource/searchResults.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/apply.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/applyResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/applyResource/scrutinyDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/summaryResource/scrutinySummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
bpa oc changes and fixed known bugs
> bpa oc changes and fixed known bugs

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/apply.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/comparisondialog.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/ComparisionLink/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/index.js
This PR includes changes related to Comparison report integration
> OAP-376: Comparison Report Changes

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/summaryResource/scrutinySummary.js
> commented applicant name

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/ComparisionLink/index.js
This PR includes changes related to comparison report option in download menu
> Comparison report download menu changes

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder-citizen/citizenSearchResource/citizenFunctions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder/searchResource/functions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/scrutinyDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/applyResource/scrutinyDetails.js
- web/rainmaker/dev-packages/egov-workflow-dev/src/ui-containers-local/WorkFlowContainer/index.js
> bpa apply issues fixed

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder-citizen/apply.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder-citizen/citizenSearchResource/citizenFunctions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder/searchResource/functions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/scrutinyDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/applyResource/scrutinyDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
- web/rainmaker/dev-packages/egov-workflow-dev/src/ui-containers-local/WorkFlowContainer/index.js
> Bpa apply issues

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/NocList/index.js
OAP-393, auto select if single doctype in the dropdown
> OAP-393, auto select if single doctype in the dropdown

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder/applyResource/declarationDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/edcrscrutiny/functions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
added edcr number in oc edcr req
> added edcr number in oc edcr req

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder/applyResource/declarationDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/edcrscrutiny/functions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/scrutinySummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
localization for sub occupancy and table
> localization for sub occupancy and table

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/index.scss
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/applyResource/index.scss
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-containers-local/PreviewContainer/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/SingleDocDetailCard/index.js
This PR contains fixes related to #OAP-392, #OAP-396, #OAP-381
> Changes relaated to  #OAP-392, #OAP-396, #OAP-381

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/searchResource/functions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/BpaDocumentList/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/NocList/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/UploadCard/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
> added new desgin to FI Docs

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/api.js
This PR includes changes related to #437
>  Commintg changes related to  #437

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder-citizen/home.js
This PR includes fix for OAP-436
> fix for OAP-436

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder-citizen/citizenSearchResource/citizenFunctions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder-citizen/my-applications-stakeholder.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/edcrscrutiny/functions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/edcrscrutiny/home.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/edcrscrutiny/my-applications-stakeholder.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/apply.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/apply.js
my application edcr view changes
> my application edcr view changes

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/edcrscrutiny/functions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/edcrscrutiny/ocapply.js
> oc edcr issues fixed

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-atoms-local/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-atoms-local/ocPermitNumber/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder-citizen/citizenSearchResource/citizenFunctions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder-citizen/my-applications-stakeholder.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/edcrscrutiny/functions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/searchResource/citizenFooter.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
> bpa oc issues fixes

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/search-preview.js
changed the position of business service
> changed the position of business service

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
> #453 changes

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder-citizen/citizenSearchResource/citizenFunctions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder-citizen/my-applications-stakeholder.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/edcrscrutiny/acknowledgement.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/edcrscrutiny/acknowledgementResource/gotoHomeFooter.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/edcrscrutiny/functions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/apply.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/summaryResource/scrutinySummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
> bpa oc fixes

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/searchResource/bpaApplication.js
> search issue fixed

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-containers-local/PreviewContainer/index.js
Changes related to regression fix
> Changes related to OAP-450

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/BpaDocumentList/index.js
> Changes related to OAP-467

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/edcrscrutiny/acknowledgement.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/edcrscrutiny/functions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/edcrscrutiny/my-applications-stakeholder.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/searchResource/bpaApplication.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/searchResource/functions.js
bpa search and edcr issues fixed
> bpa search and edcr issues fixed

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder-citizen/my-applications-stakeholder.js
> Committing the changes related to oap-491

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-containers-local/DownloadFileContainerForFI/index.js
This PR contains changes related to OAP-442
> Changes related to OAP-442

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/NocList/index.js
> #446 changes

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
revocation status name changed
> revocation status name changed

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/acknowledgement.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/acknowledgementResource/footers.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.css
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
- web/rainmaker/dev-packages/egov-common-dev/src/ui-config/screens/specs/egov-common/payResource/footer.js
- web/rainmaker/dev-packages/egov-common-dev/src/ui-containers-local/PaymentRedirectPage/index.js
Bpa permit order download after sanction fee
> Bpa permit order download after sanction fee

- web/dss-dashboard/src/components/common/Cards/CardStyles.js
- web/dss-dashboard/src/components/common/globalFilter/Style.js
- web/dss-dashboard/src/components/common/globalFilter/index.js
- web/dss-dashboard/src/components/common/inputs/ActionButtons.js
- web/dss-dashboard/src/components/common/inputs/DropDown/droapdown.js
- web/dss-dashboard/src/components/common/inputs/MultipleSelect/AutoComplete.js
- web/dss-dashboard/src/components/common/inputs/MultipleSelect/MultipleSelect.js
- web/dss-dashboard/src/components/common/inputs/MultipleSelect/backup.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/meterReading/meterReadingEditable.js
Merging master to private, so that it can be moved to Release-v3 branch
> Merging master changes to private branch

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder-citizen/my-applications-stakeholder.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.css
issues fixed in my applications
> issues fixed in my applications

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/acknowledgement.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/acknowledgementResource/footers.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/searchResource/bpaApplication.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/searchResource/functions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/basicSummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/acknowledgement.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/summaryResource/scrutinySummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
> Bpa skip payment developed

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/acknowledgement.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/acknowledgementResource/footers.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/searchResource/citizenFooter.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/acknowledgement.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.css
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/MultiDocDetailCard/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/UploadCard/index.js
> Bpa review fixes

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-atoms-local/MenuButton/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/acknowledgement.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/acknowledgement.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/search-preview.js
> 569 and 571

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
> added condition for low risk

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder-citizen/my-applications-stakeholder.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/searchResource/functions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/searchResource/searchResults.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/fieldSummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/fieldinspectionSummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/summaryResource/fieldSummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/summaryResource/fieldinspectionSummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.css
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-containers-local/PreviewContainer/index.scss
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/BpaDocumentList/index.scss
> Demoissues

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
> Fix related to docs

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder-citizen/citizenSearchResource/citizenFunctions.js
Changes related to search-preview
> Committing changes related to OAP-580

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
> Changes related to #587

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/acknowledgement.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
documents and noc akowdgement screen issues fixed
> documents and noc akowdgement screen issues fixed

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/apply.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/index.scss
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/noc.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/apply.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/NocData/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/NocDetailCard/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/NocDocDetailCard/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
- web/rainmaker/packages/employee/package.json
> BPA NOC screens

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
BPA Document upload button issue fixed
> BPA Document upload button issue fixed

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
> fixed document issue

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/applyResource/scrutinyDetails.js
> OAP-563 subOccupancyType

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-atoms-local/LinkAtom/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-atoms-local/NocNumber/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-atoms-local/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/noc-search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/noc-searchResource/nocApplication.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/noc.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/NocData/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/NocDetailCard/index.js
> Bpa noc issues

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
> noc issues

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/noc-search-preview.js
OAP-611 (Fire NOC Title is shown in Airport NOC application)
> OAP-611 (Fire NOC Title is shown in Airport NOC application)

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/noc-searchResource/searchResults.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
oap -612 (uplaod button visible and removed current owner in search)
> oap -612 (uplaod button visible and removed current owner in search)

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/applyResource/footer.js
OAP-605 (On the summary screen upload button is displayed for NOC documents)
> OAP-605 (On the summary screen upload button is displayed for NOC documents)

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/applyResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
OAP-618 (The NOC Documents order is not consistent)
> OAP-618 (The NOC Documents order is not consistent)

- web/rainmaker/dev-packages/egov-workflow-dev/src/ui-containers-local/WorkFlowContainer/index.js
OAP-625 (Footer is overlapping - architect login)
> OAP-625 (Footer is overlapping - architect login)

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
- web/rainmaker/dev-packages/egov-common-noc-dev/package.json
OAP-628(Not able to forward permit application from NOC verifier login - Document Type NOC.AIRPORT is invalid for FIRE_NOC application)
> OAP-628(Not able to forward permit application from NOC verifier login - Document Type NOC.AIRPORT is invalid for FIRE_NOC application)

- web/rainmaker/dev-packages/egov-common-noc-dev/src/ui-config/screens/specs/utils/index.js
OAP-627 (When the NOC approver uploads the documents and approves - uploaded by should be displayed as NOC Approver)
> OAP-627 (When the NOC approver uploads the documents and approves - uploaded by should be displayed as NOC Approver)

- web/rainmaker/dev-packages/egov-tradelicence-dev/src/ui-config/screens/specs/tradelicence/applyResource/tradeDetails.js
Co-authored-by: Shreya B <shreya.b@egovernments.org>
> RAIN-1336 : Removed Old License Number Search field in TL (#1733)

- web/rainmaker/dev-packages/egov-tradelicence-dev/src/ui-config/screens/specs/tradelicence/acknowledgementResource/applicationSuccessFooter.js
- web/rainmaker/dev-packages/egov-tradelicence-dev/src/ui-config/screens/specs/tradelicence/acknowledgementResource/paymentSuccessFooter.js
- web/rainmaker/dev-packages/egov-tradelicence-dev/src/ui-config/screens/specs/tradelicence/applyResource/footer.js
- web/rainmaker/dev-packages/egov-workflow-dev/src/ui-molecules-local/Footer/downloadItems.js
- web/rainmaker/dev-packages/egov-workflow-dev/src/ui-molecules-local/Footer/index.js
> New WF of TL Changes PI-7810

- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/abg/billSearchResources/searchResults.js
- web/rainmaker/dev-packages/egov-common-dev/src/ui-config/screens/specs/egov-common/payResource/footer.js
- web/rainmaker/dev-packages/egov-common-dev/src/ui-config/screens/specs/utils/index.js
1. WOR-407 : Advance carryforward implementation in common pay screen
2. RAIN-1353 : Advance Payment :: Proper validation is not done when the advance payment is done and later tried to make the Full Payment on the same bill
3. RAIN-1361 : Bill Genie :: Pay options are not displayed for the Advance paid consumer numbers.
4. RAIN-1362 : WS :: Advance Carry Forward tax head is displayed twice in the common pay screen for the advance paid consumer numbers.
> RAIN-1353 : Cherry-picking fixes to the develop branch

- web/rainmaker/dev-packages/egov-tradelicence-dev/src/ui-config/screens/specs/tradelicence/acknowledgementResource/approvalSuccessFooter.js
Download/Print TL Certificate Button enable on Approver screen PI-7810
> Download/Print TL Certificate Button enable on Approver screen PI-7810

- web/rainmaker/dev-packages/egov-tradelicence-dev/src/ui-config/screens/specs/tradelicence/acknowledgement.js
Disabled TL-Certificate after send back application PI-7810
> Disabled TL-Certificate after send back application PI-7810

- web/rainmaker/dev-packages/egov-tradelicence-dev/src/ui-config/screens/specs/tradelicence/acknowledgement.js
Disabled TL-Certificate after send back application PI-7910
> Disabled TL-Certificate after send back application PI-7910

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
https://docs.google.com/document/d/1FxdrIY3BSJxZH3JWuilQ1OSCicozjENeDbgTJY7A498/edit?ts=5f2cf1d1 (NOC DOCUMENTS ISSUE)
> OAP-601 (NOC UI ISSUES)

- web/rainmaker/dev-packages/egov-common-dev/src/ui-containers-local/CustomTabContainer/index.js
…ed for owner when the payer name for owner is changed once.
> RAIN-1365 : Fixed Common pay :: The payer name is not coming autofilled after altering owner name

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
> OAP-633(NOC issues)

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/UploadCard/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
- web/rainmaker/dev-packages/egov-noc-dev/src/ui-molecules-local/UploadCard/index.js
> OAP-633(NOC issues) 

- web/rainmaker/packages/employee/src/config/forms/specs/PropertyTaxPay/chequeInfo.js
Update disabled false for IFSC code PI-8162
> Update disabled false for IFSC code PI-8162

- web/rainmaker/packages/employee/src/config/forms/specs/PropertyTaxPay/chequeInfo.js
Update BankName property and BankBranch property PI-8162
> Update BankName property and BankBranch property PI-8162

- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-mutation/apply.js
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-mutation/index.scss
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-mutation/search-preview.js
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-molecules-local/Table/index.scss
- web/rainmaker/dev-packages/egov-ui-framework-core/src/ui-molecules/Table/index.css
- web/rainmaker/dev-packages/egov-ui-kit-dev/src/common/propertyTax/PTAcknowledgement/index.scss
- web/rainmaker/dev-packages/egov-ui-kit-dev/src/common/propertyTax/YearDialogue/components/RadioButtonForm/index.js
- web/rainmaker/dev-packages/pt-citizen-dev/src/Screens/ReviewForm/components/PaymentAmountDetails/index.js
- web/rainmaker/dev-packages/pt-citizen-dev/src/Screens/common/YearDialogue/components/RadioButtonForm/index.js
- web/rainmaker/dev-packages/pt-employee-dev/src/Screens/FormWizard/components/ReviewForm/components/AdditionalDetails/index.js
* RAIN-1470 : PT-Mutation Apk Misalignment Issues fix
* RAIN-1470 : PT Apk Issue for Table Misalignment fix
* RAIN-1470 : PT APK issue fix for Search Preview screen
* RAIN-1470 : PT APK issue fix for PT Create acknowledgement alignment
* RAIN-1470 : PT Mutation Apply screen apk issue fix
* RAIN-1470 : PT Assess Year Popup Apk issue fix
> RAIN-1470 : PT Apk css issue fixes  (#1952)

- web/dss-dashboard/src/components/Charts/CollectionChartRow.js
- web/dss-dashboard/src/components/Dashboard/dashboard.js
- web/dss-dashboard/src/utils/block.js
- web/rainmaker/dev-packages/egov-ui-kit-dev/src/common/propertyTax/Property/components/OwnerInfo/index.js
- web/rainmaker/dev-packages/egov-ui-kit-dev/src/utils/PTCommon/FormWizardUtils/formUtils.js
- web/rainmaker/dev-packages/egov-ui-kit-dev/src/utils/commons.js
* RAIN-1512 : PT Owner sort by alphabetically in edit screen
* RAIN-1493 : PGR localisation Fix
* RAIN-1493 : DSS Download in overview card fix
* RAIN-1493 : DSS apk issue fix for horizontal scroll
* RAIN-1493: DSS apk issue fix for Overview Card overflow text
> Rain 1493 : DSS Apk CSS Alignment issue fix  (#1954)

- web/rainmaker/dev-packages/egov-tradelicence-dev/src/ui-config/screens/specs/tradelicence/acknowledgementResource/applicationSuccessFooter.js
Redirect Search preview page PI-8071
> Redirect Search preview page PI-8071

- web/rainmaker/dev-packages/egov-firenoc-dev/src/ui-config/screens/specs/fire-noc/summaryResource/footer.js
- web/rainmaker/dev-packages/egov-firenoc-dev/src/ui-utils/commons.js
RAIN-1661 (Fire Noc :: Blank screen is displayed on the summary screen while creating new fire noc application.)
> RAIN-1661 (Fire Noc :: Blank screen is displayed on the summary screen while creating new fire noc application.)

- web/rainmaker/dev-packages/pgr-employee-dev/src/Screens/AllComplaints/index.css
- web/rainmaker/dev-packages/pgr-employee-dev/src/Screens/AllComplaints/index.scss
RAIN-1585 (PGR Apk :: Search and sort option is not there in GRO Login)
> RAIN-1585 (PGR Apk :: Search and sort option is not there in GRO Login)

- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/apply.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/applyResource/amountDetails.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/applyResource/documentDetails.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/applyResource/footer.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/utils/index.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-containers-local/DocumentListContainer/index.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-containers-local/index.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-molecules-local/DocumentList/index.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-molecules-local/UploadSingleFile/index.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-molecules-local/index.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-utils/commons.js
RAIN-1681(Bill Amendment UI: Dynamic Documents upload screen integration)
> RAIN-1681(Bill Amendment UI: Dynamic Documents upload screen integration)

- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/apply.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/applyResource/amountDetails.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-containers-local/AdjustmentAmountContainer/index.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-containers-local/CheckBoxContainer/index.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-containers-local/index.js
RAIN-1614(added amount details stepper)
> RAIN-1614(added amount details stepper)

- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/apply.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/applyResource/amountDetails.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-containers-local/index.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-molecules-local/index.js
RAIN-1674 (Bill Amendment UI: MDMS Config Creation and Integration reg demandBasis)
> RAIN-1674 (Bill Amendment UI: MDMS Config Creation and Integration reg demandBasis)

- web/rainmaker/dev-packages/egov-hrms-dev/src/ui-config/screens/specs/hrms/searchResource/searchForm.js
- web/rainmaker/dev-packages/egov-hrms-dev/src/ui-config/screens/specs/utils/index.css
RAIN-1715 (HRMS :: Reset and search buttons are not aligned properly in mobile view.)
> RAIN-1715 (HRMS :: Reset and search buttons are not aligned properly in mobile view.)

- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/applyResource/amountDetails.js
RAIN-1751 (Bill Amendment :: All dependent fields for Demand Basis Card for few options is not proper.)
> RAIN-1751 (Bill Amendment :: All dependent fields for Demand Basis Card for few options is not proper.)

- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-containers-local/AdjustmentAmountContainer/index.js
RAIN-1750(Bill Amendment :: UI Alignment Issue in Reduced and Additional amount entered in box.)
> RAIN-1750(Bill Amendment :: UI Alignment Issue in Reduced and Additional amount entered in box.)

- web/rainmaker/dev-packages/egov-hrms-dev/src/ui-config/themes/index.js
- web/rainmaker/dev-packages/egov-ui-framework-core/src/ui-molecules/Table/index.css
RAIN-1716 (HRMS :: No details are displayed in mobile view for the searched result.)
> RAIN-1716 (HRMS :: No details are displayed in mobile view for the searched result.)

- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-mutation/applyResourceMutation/transfereeDetails.js
RAIN-954 (PT Mutation :: Able to select the different Document Type  for the special applicant type while creating mutation application)
> RAIN-954 (PT Mutation :: Able to select the different Document Type  for the special applicant type while creating mutation application)

- web/rainmaker/dev-packages/egov-tradelicence-dev/src/ui-config/screens/specs/tradelicence/search-preview.js
- web/rainmaker/dev-packages/egov-tradelicence-dev/src/ui-molecules-local/DocumentList/index.js
- web/rainmaker/packages/employee/src/modules/employee/Inbox/components/Table/index.js
- web/rainmaker/packages/employee/src/modules/employee/Inbox/components/TableData/index.js
RAIN-1382 (Trade License: Document upload issue)
> RAIN-1382 (Trade License: Document upload issue)

- web/rainmaker/packages/employee/src/modules/employee/reports/reportResult.js
RAIN-1537 (PGR Reports :: Object Object is displayed in the first rowin the downloaded excel for ULB Reports.)
> RAIN-1537 (PGR Reports :: Object Object is displayed in the first rowin the downloaded excel for ULB Reports.)

- web/rainmaker/packages/employee/src/modules/employee/Inbox/components/Table/index.js
- web/rainmaker/packages/employee/src/modules/employee/Inbox/components/TableData/index.js
- web/rainmaker/packages/employee/src/modules/employee/Inbox/components/actionItems.js
RAIN-1818 : Inbox sorting issue reolved and Initial loading records have been changed
> RAIN-1818 : Inbox sorting issue reolved and Initial loading records have been changed

- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-mutation/apply.js
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-mutation/applyResource/footer.js
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-mutation/applyResourceMutation/transfereeDetails.js
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-mutation/search-preview.js
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-mutation/summaryResource/transfereeSummary.js
- web/rainmaker/dev-packages/egov-ui-kit-dev/src/common/common/ActionMenu/components/index.js
- web/rainmaker/dev-packages/egov-ui-kit-dev/src/hocs/withAuthorization.js
- web/rainmaker/dev-packages/egov-ui-kit-dev/src/redux/app/actions.js
- web/rainmaker/dev-packages/egov-ui-kit-dev/src/utils/localStorageUtils/index.js
* Revert "RAIN-1790 : PT Mutation Correction in Owner Details Issue fix"
This reverts commit 0456f10443b355d73cb5c5503e842470f2ffa209.
* Revert "RAIN-1624 : Localisation caching implementation (#2040)"
This reverts commit aac28818c1f968f43d9012539556d9c5d20971d5.
* RAIN-1817 : PT Mutation Mutli owner Issue fix in summary screen
> PT Mutation Mutli owner Issue fix in summary screen (#2043)

- web/rainmaker/dev-packages/egov-common-dev/src/ui-containers-local/CustomTabContainer/payment-methods.js
The payment is being paid without bank name & bank branch name in cheque mode and DD also.
> Update validation on bank name & bank branch PI-8607, PI-8606, PI-8298

- web/rainmaker/dev-packages/egov-hrms-dev/src/ui-config/screens/specs/hrms/createResource/assignment-details.js
- web/rainmaker/dev-packages/egov-hrms-dev/src/ui-config/screens/specs/hrms/createResource/employee-details.js
- web/rainmaker/dev-packages/egov-hrms-dev/src/ui-config/screens/specs/hrms/createResource/jurisdiction-details.js
- web/rainmaker/dev-packages/egov-hrms-dev/src/ui-config/screens/specs/hrms/createResource/other-details.js
RAIN-1846 ( HRMS :: All employee details are not displayed wile edit the employee )
> RAIN-1846 ( HRMS :: All employee details are not displayed wile edit the employee )

- web/rainmaker/dev-packages/egov-hrms-dev/src/ui-config/screens/specs/hrms/create.js
RAIN-1845 (HRMS :: Alternative years are listed for Education Qualification and Department Test Details.)
> RAIN-1845 (HRMS :: Alternative years are listed for Education Qualification and Department Test Details.)

- web/rainmaker/packages/employee/src/modules/employee/reports/reportResult.js
RAIN-1563 (PGR Reports :: Not able to download the reports in XLS format)
> RAIN-1563 (PGR Reports :: Not able to download the reports in XLS format)

- web/rainmaker/dev-packages/egov-ui-kit-dev/src/hocs/withAuthorization.js
- web/rainmaker/dev-packages/egov-ui-kit-dev/src/redux/app/actions.js
RAIN-1821 (Entire page elements are displayed in code once the user does the hard refresh or multiple refresh.)
> RAIN-1821 (Entire page elements are displayed in code once the user does the hard refresh or multiple refresh.)

- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/applyResource/documentDetails.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/applyResource/footer.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/applyResource/summary.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/utils/index.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-containers-local/AdjustmentAmountContainer/index.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-containers-local/DocumentListContainer/index.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-molecules-local/DocumentList/index.js
RAIN-1679 (Bill Amendment UI: Generate Note Form wizard + Mobile view)
> RAIN-1679 (Bill Amendment UI: Generate Note Form wizard + Mobile view)

- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-common-screens/applyResource/footer.js
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-common-screens/propertySearch.js
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-common-screens/register-property.js
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-common-screens/searchResource/searchResults.js
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-common-screens/summary.js
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-common-screens/summaryResource/propertyAssemblySummary.js
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-common-screens/summaryResource/propertyLocationSummary.js
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-common-screens/summaryResource/propertyOwnershipSummary.js
RAIN-1772 (W&S Property workflow config)
> RAIN-1772 (W&S Property workflow config)

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
RAIN-1931 (UI Update the Collection service API URL to new URL with business Service)
> RAIN-1931 (UI Update the Collection service API URL to new URL with business Service)

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder/applyResource/documentList.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/DocumentList/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/UploadCard/index.js
OAP-637 (System allowing all type of files)
> OAP-637 (System allowing all type of files)

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/CheckList/index.js
OAP-636 (In OC document section in the remarks column tenant name by default showing)
> OAP-636 (In OC document section in the remarks column tenant name by default showing)

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/apply.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-utils/commons.js
> RAIN-1809 (UI: W&S Property workflow config)

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-common-screens/applyResource/footer.js
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-common-screens/applyResourceMutation/propertyAssemblyDetails.js
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-common-screens/summaryResource/propertyAssemblySummary.js
RAIN-1980 (W&S :: PT Create :: Few of the entered details are not displayed in property summary page.)
> RAIN-1980 (W&S :: PT Create :: Few of the entered details are not displayed in property summary page.)

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/reviewConnectionDetails.js
RAIN-1983 (W&S :: PT Create :: On Summary screen , wrong details are reflected for multiple owner information.)
> RAIN-1983 (W&S :: PT Create :: On Summary screen , wrong details are reflected for multiple owner information.)

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/NocDetailCard/index.js
OAP-638 (Issues in Occupancy certificate apply and process screens)
> OAP-638 (Issues in Occupancy certificate apply and process screens)

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-common-screens/summaryResource/propertyAssemblySummary.js
OAP-646 (Upload button for the documents uploaded card is available for all employees)
> OAP-646 (Upload button for the documents uploaded card is available for all employees)

- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-common-screens/applyResourceMutation/propertyAssemblyDetails.js
RAIN-1986 (W&S :: Sub Usage category being non mandatory is mandatory.)
> RAIN-1986 (W&S :: Sub Usage category being non mandatory is mandatory.)

- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-common-screens/summaryResource/propertyOwnershipSummary.js
RAIN-1997 (W&S :: Owner Details of Institutional Private and Institutional Details are not proper in Connection details page.)
> RAIN-1997 (W&S :: Owner Details of Institutional Private and Institutional Details are not proper in Connection details page.)

- web/rainmaker/dev-packages/egov-common-dev/src/ui-config/screens/specs/egov-common/acknowledgementResource/paymentFooter.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/public-search.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/publicSearchResource/publicSearchUtils.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/publicSearchResource/search-methods.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/publicSearchResource/search-resources.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/publicSearchResource/searchApplicationResult.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-utils/commons.js
- web/rainmaker/packages/citizen/src/modules/App.js
RAIN-1858 (W&S - Public Domain Search)
> RAIN-1858 (W&S - Public Domain Search)

- web/rainmaker/dev-packages/egov-hrms-dev/src/ui-config/screens/specs/hrms/searchResource/searchForm.js
Update drop-down in HRMS PI-8762
> Update drop-down in HRMS PI-8762

- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-common-screens/applyResource/footer.js
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-common-screens/summaryResource/propertyAssemblySummary.js
RAIN-2022 (W&S :: Not able to create a new property with residential and Mixed property usage type.)
> RAIN-2022 (W&S :: Not able to create a new property with residential and Mixed property usage type.)

- web/rainmaker/dev-packages/egov-noc-dev/src/ui-molecules-local/HowItWorks/index.js
- web/rainmaker/packages/citizen/src/modules/Routes/citizen.js
- web/rainmaker/packages/citizen/src/ui-views/HowItWorks/index.js
Addition of Fire NOC - Employee User Manual in Citizen login PI-8857
> Addition of Fire NOC - Employee User Manual in Citizen login PI-8857

- web/rainmaker/dev-packages/egov-hrms-dev/src/ui-config/screens/specs/hrms/searchResource/searchForm.js
Add search by Mobile in HRMS (PI-6224, PI-8744)
> Add search by Mobile in HRMS (PI-6224, PI-8744)

- web/rainmaker/dev-packages/egov-ui-kit-dev/src/utils/commons.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/publicSearchResource/publicSearchUtils.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/publicSearchResource/search-methods.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/publicSearchResource/search-resources.js
> RAIN-2043 && RAIN-2042 WNS Open search and Payment changes

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-utils/commons.js
> RAIN-2100 WNS Docu upload issue fix

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/task-connectiondetails.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/search-preview.js
W&S :: Water Related details are there in Search preview page for Sewerage Connection.
> RAIN-2072 (W&S :: Water Related details are there in Search preview page for Sewerage Connection.)

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/publicSearchResource/publicSearchUtils.js
> RAIN-2101 (W&S :: Public Domain Search :: Payer Name and mobile number are not auto populating in Common Pay Page.)

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-atoms-local/downloadFile/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/edcrscrutiny/acknowledgementResource/acknowledgementUtils.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/search-preview.js
OAP-645 (scrutiny report is not working in OBPS)
> OAP-645 (scrutiny report is not working in OBPS)

- web/rainmaker/dev-packages/egov-wns-dev/src/index.scss
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/index.scss
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/public-search.js
- web/rainmaker/packages/citizen/src/ui-views/ScreenInterface/index.scss
RAIN-2113 (W&S :: Public Domain Search :: Apk Alignment Issues)
> RAIN-2113 (W&S :: Public Domain Search :: Apk Alignment Issues)

- web/rainmaker/dev-packages/egov-common-dev/src/ui-config/screens/specs/egov-common/download-receipt.js
- web/rainmaker/dev-packages/egov-common-dev/src/ui-utils/commons.js
- web/rainmaker/dev-packages/egov-hrms-dev/src/ui-config/screens/specs/hrms/createResource/employee-details.js
- web/rainmaker/dev-packages/egov-hrms-dev/src/ui-config/screens/specs/hrms/viewResource/functions.js
- web/rainmaker/dev-packages/egov-hrms-dev/src/ui-molecules-local/UploadMultipleFiles/index.js
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-common-screens/applyResource/footer.js
- web/rainmaker/dev-packages/egov-uc-dev/src/ui-config/screens/specs/uc/universalCollectionResources/function.js
- web/rainmaker/dev-packages/egov-uc-dev/src/ui-config/screens/specs/uc/universalCollectionResources/searchResults.js
- web/rainmaker/dev-packages/egov-ui-framework-core/src/ui-molecules/UploadMultipleFiles/index.js
- web/rainmaker/dev-packages/egov-ui-kit-dev/src/utils/localStorageUtils/index.js
* RAIN-2115 : WNS create property issue fix for shared property.
* RAIN-2115 ; Common pay redirection for download recipt from whatsapp
* RAIN-2115 : HRMS Upload documents issue fix incase of Activation and deactivation
* RAIN-2115 : UC download receipt in search result screen
* RAIN-2115 : Common on lick of logout removed all cache data
> RAIN-2115 : WNS create property issue fix for shared property. (#2169)

- web/rainmaker/dev-packages/egov-hrms-dev/src/ui-config/screens/specs/hrms/createResource/assignment-details.js
Dropdown option in HRMS PI-8229
> Dropdown option in HRMS PI-8229

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-atoms-local/downloadFile/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/edcrscrutiny/acknowledgementResource/acknowledgementUtils.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/search-preview.js
Oap 645 (scrutiny report is not working in OBPS)
> Oap 645 (scrutiny report is not working in OBPS)

- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-common-screens/searchResource/searchResults.js
RAIN-2119 (W&S:: In Workflow selection is not happening in property searched result.)
> RAIN-2119 (W&S:: In Workflow selection is not happening in property searched result.)

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
OAP-650 (collection search URL when download receipts)
> OAP-650 (collection search URL when download receipts)

- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/apply.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/applyResource/amountDetails.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/applyResource/footer.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/utils/index.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-containers-local/AdjustmentAmountContainer/index.js
Rain 1680 (Bill Amendment UI: Apply screen integration with API + validation)
> Rain 1680 (Bill Amendment UI: Apply screen integration with API + validation)

- web/rainmaker/dev-packages/egov-ui-kit-dev/src/utils/pdfUtils/generatePDF.js
* RAIN-2120 TL receipt tryout
* RAIN-2120 : Generate PDF for Mobile apk blob issue fix
> RAIN-2120 : Generate PDF for Mobile apk blob issue fix (#2189)

- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/acknowledgement.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/apply.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/applyResource/footer.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/applyResource/summary.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/search-preview.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/utils/index.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-containers-local/AdjustmentAmountContainer/index.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-containers-local/EstimateCardContainer/index.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-molecules-local/FeeEstimateCard/index.js
RAIN-1680 (Bill Amendment UI: Apply screen integration with API + validation)
> RAIN-1680 (Bill Amendment UI: Apply screen integration with API + validation)

- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/search.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/searchResources/function.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/searchResources/searchCard.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/searchResources/searchResults.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-utils/commons.js
- web/rainmaker/dev-packages/egov-ui-framework-core/src/ui-atoms/TextFields/Text/index.js
* RAIN-1676 : Bill Amend Search screen integration
* RAIN-1676 : Bill Amendment updated helper text fontsize to1.4
> RAIN-1676 : Bill Amend Search screen integration  (#2201)

- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/applyResource/amountDetails.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/applyResource/footer.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/applyResource/summary.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/search-preview.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/utils/index.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-molecules-local/FeeEstimateCard/index.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-utils/commons.js
RAIN-1678 (Amendment UI: Search preview integration )
> RAIN-1678 (Amendment UI: Search preview integration )

- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/applyResource/footer.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-molecules-local/FeeEstimateCard/index.js
RAIN-1678 (Bill Amendment UI: Search preview integration)
> RAIN-1678 (Bill Amendment UI: Search preview integration)

- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/search-preview.js
- web/rainmaker/dev-packages/egov-workflow-dev/src/ui-containers-local/WorkFlowContainer/index.js
RAIN-2158 (Bill Amendment UI: Workflow Integration)
> RAIN-2158 (Bill Amendment UI: Workflow Integration)

- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/acknowledgement.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/acknowledgementResource/approvalSuccessFooter.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/utils/index.js
RAIN-2158 (changing the acknowledgment screen for approve and reject)
> RAIN-2158 (changing the acknowledgment screen for approve and reject)

- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/apply.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/applyResource/footer.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/search-preview.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/utils/index.js
RAIN-1678 (filtering non zero values)
> RAIN-1678 (filtering non zero values)

- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/search-preview.js
RAIN-1678-3 (setting the consumer as dynamic)
> RAIN-1678-3 (setting the consumer as dynamic)

- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/apply.js
RAIN-2174 (Bill Amendment :: Cached upload files are there while creating a new amendment.)
> RAIN-2174 (Bill Amendment :: Cached upload files are there while creating a new amendment.)

- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-containers-local/AdjustmentAmountContainer/index.js
RAIN-2180 (Bill Amendment ::UI Validation is not there on entering Wrong amount type.)
> RAIN-2180 (Bill Amendment ::UI Validation is not there on entering Wrong amount type.)

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder-citizen/home.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/edcrscrutiny/functions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/search-preview.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
OAP-647 (Declaration in citizen workflow not working)
> OAP-647 (Declaration in citizen workflow not working)

- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/apply.js
RAIN-2192 (Bill Amendment :: Only few of the Tax heads are displayed while creating a new Bill Amendment.)
> RAIN-2192 (Bill Amendment :: Only few of the Tax heads are displayed while creating a new Bill Amendment.)

- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/search-preview.js
RAIN-2181 : Bill Amend Saearch preview download coupon fix
> RAIN-2181 : Bill Amend Saearch preview download coupon fix

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/edcrscrutiny/home.js
RAIN-2186 (Citizen can access the features meant for an architect)
> RAIN-2186 (Citizen can access the features meant for an architect)

- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/utils/index.js
RAIN-2200 (Bill Amendment :: Not able to create new Bill Amendement from UI.)
> RAIN-2200 (Bill Amendment :: Not able to create new Bill Amendement from UI.)

- web/rainmaker/dev-packages/egov-uc-dev/src/ui-config/screens/specs/uc-citizen/receiptsResources/function.js
- web/rainmaker/dev-packages/egov-uc-dev/src/ui-config/screens/specs/uc-citizen/search.js
RAIN-2194 (UC :: PT, TL and WS related receipts are displayed when searched by mobile number from Citizen Login)
> RAIN-2194 (UC :: PT, TL and WS related receipts are displayed when searched by mobile number from Citizen Login)

- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/apply.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/applyResource/amountDetails.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/applyResource/footer.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/applyResource/summary.js
- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/utils/index.js
RAIN-2245 (Bill Amendment UI Alignment Issues)
> RAIN-2245 (Bill Amendment UI Alignment Issues)

- web/rainmaker/dev-packages/egov-common-dev/src/ui-config/screens/specs/egov-common/payResource/footer.js
> revert RAZORPAY related code

- web/rainmaker/dev-packages/egov-common-dev/src/ui-config/screens/specs/egov-common/payResource/footer.js
Allow multiple pg according to ULB
> Allow multiple pg according to ULB

- web/rainmaker/dev-packages/egov-billamend-dev/src/ui-config/screens/specs/bill-amend/apply.js
This reverts commit c937cc6d439fcb678b021dce33647392961f6fdb.
> RAIN-2247 : Bill Amend Added a New Taxhead changes - Reverted

- web/rainmaker/dev-packages/egov-common-dev/src/ui-config/screens/specs/egov-common/payResource/footer.js
replace dynamic param for live transaction
> replace dynamic param for live transaction

- web/rainmaker/dev-packages/egov-ui-kit-dev/src/utils/pdfUtils/generateWSAcknowledgement.js
- web/rainmaker/dev-packages/egov-wns-dev/src/index.scss
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/additionalDetails.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/footer.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/index.scss
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/review-owner.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/reviewOwner.js
RAIN-2223 (W&S : Multiple road type support)
> RAIN-2223 (W&S : Multiple road type support)

- web/rainmaker/dev-packages/egov-ui-framework-core/src/ui-containers/MultiItem/index.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/footer.js
> RAIN-2223 (null checking in multiitem for resolving rendering issues

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/footer.js
RAIN-2277 (WS :: Blank screen is displayed for Summary screen while creating water and sewerage application)
> RAIN-2277 (WS :: Blank screen is displayed for Summary screen while creating water and sewerage application)

- web/rainmaker/dev-packages/egov-hrms-dev/src/ui-config/screens/specs/hrms/search.js
- web/rainmaker/dev-packages/egov-hrms-dev/src/ui-config/screens/specs/utils/index.js
RAIN-2248 (HRMS :: Without selecting city from Pick Your City popup able to proceed further while creating employee.)
> RAIN-2248 (HRMS :: Without selecting city from Pick Your City popup able to proceed further while creating employee.)

- web/rainmaker/dev-packages/egov-tradelicence-dev/src/ui-config/screens/specs/tradelicence/applyResource/footer.js
Update param value for EODB integration
> Update param value for EODB integration

- web/rainmaker/dev-packages/egov-ui-kit-dev/src/redux/auth/actions.js
- web/rainmaker/packages/citizen/package.json
RAIN-2286 (Security: Frontend change to integrate with new structure of logout API)
> RAIN-2286 (Security: Frontend change to integrate with new structure of logout API)

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/search-preview.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-utils/commons.js
Rain 2317 ( Water and Sewerage: Addition of Property Unique Id instead of Property UUID to handle the property mutation usecase)
> Rain 2317 ( Water and Sewerage: Addition of Property Unique Id instead of Property UUID to handle the property mutation usecase)

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/apply.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/functions.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-utils/commons.js
RAIN-2317 (Showing active owners)
> RAIN-2317 (Showing active owners)

- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-common-screens/applyResource/footer.js
RAIN-2330 (WS:: while creating a property to apply for water connection -incorrect validation is shown)
> RAIN-2330 (WS:: while creating a property to apply for water connection -incorrect validation is shown)

- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-common-screens/searchResource/searchFunctions.js
RAIN-2351 (W&S :: Both Old Owner and New Owner is reflected in the property search result.)
> RAIN-2351 (W&S :: Both Old Owner and New Owner is reflected in the property search result.)

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/apply.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/footer.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/search-preview.js
RAIN-2329 (WS:: When the doc verifier tries to edit the application 2nd time, previously added details are not available)
> RAIN-2329 (WS:: When the doc verifier tries to edit the application 2nd time, previously added details are not available)

- web/rainmaker/dev-packages/egov-pt-dev/src/ui-utils/commons.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/footer.js
RAIN-2356 (W&S :: Download and Print Button are not functional on Submit Success screen.)
> RAIN-2356 (W&S :: Download and Print Button are not functional on Submit Success screen.)

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-molecules-local/Applications/index.js
RAIN-2357 (W&S :: No Applications and connections are displayed in Citizen's My Applications.)
> RAIN-2357 (W&S :: No Applications and connections are displayed in Citizen's My Applications.)

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/additionalDetails.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/footer.js
RAIN-2358 (WS :: Modify Effective Date should have mandatory symbol while modifying connection)
> RAIN-2358 (WS :: Modify Effective Date should have mandatory symbol while modifying connection)

- web/rainmaker/dev-packages/egov-ui-kit-dev/src/utils/pdfUtils/generateWSAcknowledgement.js
RAIN-2361 (W&S :: Intermittent Issue :: Road Cutting Changes is coming as NA for few of the Applications.)
> RAIN-2361 (W&S :: Intermittent Issue :: Road Cutting Changes is coming as NA for few of the Applications.)

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/connectionDetailsResource/service-details.js
RAIN-2363 (W&S :: "Unit of Measurement " Field is shown as Blank in connection details page .)
> RAIN-2363 (W&S :: "Unit of Measurement " Field is shown as Blank in connection details page .)

- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-common-screens/applyResource/footer.js
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-common-screens/summaryResource/propertyAssemblySummary.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/apply.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/functions.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-utils/commons.js
RAIN-2355 (WS :: Property sub usage type is displayed as NA on connection details page)
> RAIN-2355 (WS :: Property sub usage type is displayed as NA on connection details page)

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/footer.js
RAIN-2369 (WS :: Intermittent issue :: Road cutting charges details are not displayed while editing from Doc Verifier)
> RAIN-2369 (WS :: Intermittent issue :: Road cutting charges details are not displayed while editing from Doc Verifier)

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/apply.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/connectionDetails.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-containers-local/CheckboxContainer/index.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-containers-local/DocumentListContainer/index.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-molecules-local/DocumentList/index.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-molecules-local/UploadSingleFile/index.js
RAIN-2362 (WS :: Paid successfully is displayed for the amount when the application is edited while activating the connection)
> RAIN-2362 (WS :: Paid successfully is displayed for the amount when the application is edited while activating the connection)

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns-citizen/searchResource/searchResults.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/connection-details.js
RAIN-2371 (WS :: Citizen is not able to access the application as consumer code is not available in hyperlink format)
> RAIN-2371 (WS :: Citizen is not able to access the application as consumer code is not available in hyperlink format)

- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-common-screens/applyResourceMutation/propertyAssemblyDetails.js
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-common-screens/applyResourceMutation/propertyLocationDetails.js
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-common-screens/applyResourceMutation/propertyOwnershipDetails.js
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-common-screens/index.scss
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-common-screens/register-property.js
- web/rainmaker/dev-packages/egov-wns-dev/src/index.scss
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-atoms-local/AutoSuggest/index.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns-citizen/searchResource/citizenApplication.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/apply.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/additionalDetails.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/connectionDetails.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/index.scss
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/searchResource/employeeApplication.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/searchResource/searchApplications.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-containers-local/AutosuggestContainer/index.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-containers-local/index.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-molecules-local/DocumentList/index.js
RAIN-2365 (WS :: Type and Search is not available for drop down fields in Water & Sewerage module)
> RAIN-2365 (WS :: Type and Search is not available for drop down fields in Water & Sewerage module)

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/apply.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/additionalDetails.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/footer.js
RAIN-2366 (WS :: Additional details page should have mandatory mark for mandatory fields)
> RAIN-2366 (WS :: Additional details page should have mandatory mark for mandatory fields)

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/apply.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/footer.js
RAIN-2404, RAIN-2406 (Same application number is shown twice on the acknowledgement screen on first modifying the Sewerage connection)
> RAIN-2404, RAIN-2406 (Same application number is shown twice on the acknowledgement screen on first modifying the Sewerage connection)

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/footer.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/search-preview.js
- web/rainmaker/dev-packages/egov-workflow-dev/src/ui-containers-local/WorkFlowContainer/index.js
RAIN-2406 (W&S :: Road Cuttting is added while editing and removing from DV,FI.)
> RAIN-2406 (W&S :: Road Cuttting is added while editing and removing from DV,FI.)

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/edcrscrutiny/functions.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/api.js
OAP-656 (Security issue fix: Send auth-token for EDCR API's)
> OAP-656 (Security issue fix: Send auth-token for EDCR API's)

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/apply.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/apply.js
RDS-132 (Mohalla drop-down data is loading properly in BPA)
> RDS-132 (Mohalla drop-down data is loading properly in BPA)

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/search-preview.js
RAIN-2472 (WS :: Sewerage application Details are not displayed whileverifying from Doc Verifier)
> RAIN-2472 (WS :: Sewerage application Details are not displayed whileverifying from Doc Verifier)

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/search-preview.js
RAIN-2473 (WS :: Not able to Sendback or Verify and Forward Sewerage application)
> RAIN-2473 (WS :: Not able to Sendback or Verify and Forward Sewerage application)

- web/rainmaker/dev-packages/egov-common-dev/src/ui-config/screens/specs/egov-common/payResource/footer.js
> Update RAZORPAY related code

- web/rainmaker/dev-packages/egov-common-dev/src/ui-config/screens/specs/egov-common/payResource/footer.js
> Active RAZORPAY

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/edcrscrutiny/acknowledgementResource/gotoHomeFooter.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/viewBillResource/viewBillFooter.js
RAIN-2539 (WnS : Redirecting to wrong connection or collection page from search results.)
> RAIN-2539 (WnS : Redirecting to wrong connection or collection page from search results.)

- web/rainmaker/dev-packages/egov-common-dev/src/ui-containers-local/PaymentRedirectPage/index.js
> Update Transaction id

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/connectionDetailsResource/service-details.js
RAIN-2539-2 (WnS : Redirecting to wrong connection or collection page from search results.)
> RAIN-2539-2 (WnS : Redirecting to wrong connection or collection page from search results.)

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/search-preview.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-utils/commons.js
RDS-141 DIGIT WnS : Estimation charges to be shown from saved for submitted or approved applications
> RDS-141 DIGIT WnS : Estimation charges to be shown from saved for submitted or approved applications

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/adhocPopupViewBill.js
RDS-141 added cosumer code for add rebate penality
> RDS-141 added cosumer code for add rebate penality

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-containers-local/AutosuggestContainer/index.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-utils/commons.js
RAIN-2556 in the upload document page dropdown values are not showing instead keys are showing
> RAIN-2556 in the upload document page dropdown values are not showing instead keys are showing

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/bpastakeholder/applyResource/tradeOwnerDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-common-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-mutation/applyResourceMutation/mutationDetails.js
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-mutation/applyResourceMutation/registrationDetails.js
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-mutation/applyResourceMutation/transferorDetails.js
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-tradelicence-dev/src/ui-config/screens/specs/tradelicence/applyResource/tradeOwnerDetails.js
- web/rainmaker/dev-packages/egov-ui-framework-core/src/ui-utils/commons.js
- web/rainmaker/dev-packages/egov-ui-kit-dev/src/redux/auth/actions.js
- web/rainmaker/dev-packages/egov-ui-kit-dev/src/utils/api.js
- web/rainmaker/dev-packages/egov-ui-kit-dev/src/utils/commons.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/tradeOwnerDetails.js
RAIN-2206 : Security Fixes VUL-WEB-H003 removed user search from ui
> RAIN-2206 : Security Fixes VUL-WEB-H003 removed user search from ui

- web/rainmaker/dev-packages/egov-hrms-dev/src/ui-config/screens/specs/hrms/create.js
update tenantId for mdms service call
> update tenantId for mdms service call

- web/rainmaker/dev-packages/egov-tradelicence-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-tradelicence-dev/src/ui-utils/commons.js
RAIN-2542 TL :: Structure sub type field value is not auto-populated while editing from Doc Verfier
> RAIN-2542 TL :: Structure sub type field value is not auto-populated while editing from Doc Verfier

- web/rainmaker/dev-packages/egov-common-dev/src/ui-config/screens/specs/egov-common/payResource/footer.js
Add  other ULB for RAZORPAY ACTIVATE
> Add  other ULB for RAZORPAY ACTIVATE

- web/rainmaker/dev-packages/egov-ui-kit-dev/src/utils/api.js
- web/ui-uploader/src/api/index.js
> RAIN-2206 : Security Issue updated the Basic Auth Token which was req…,

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/additionalDetails.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/ownerDetails.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/review-owner.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/review-trade.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/reviewConnectionDetails.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/reviewOwner.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/task-connectiondetails.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/connectionDetailsResource/service-details.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/searchResource/searchApplications.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/viewBillResource/serviceDetails.js
RAIN-2703 WNS Localization :: English messages are displayed on Old UI if Hindi is selected
> RAIN-2703 WNS Localization issue fix in few Label pairs

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/additionalDetails.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/ownerDetails.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/review-owner.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/review-trade.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/reviewConnectionDetails.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/reviewOwner.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/task-connectiondetails.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/connectionDetailsResource/service-details.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/meterReading/meterReadingEditable.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/searchResource/searchApplications.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/viewBillResource/serviceDetails.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-molecules-local/MeterReading/index.js
Rain 2703 WNS Localization :: English messages are displayed on Old UI if Hindi is selected
> Rain 2703 WNS Localization :: English messages are displayed on Old UI if Hindi is selected

- web/rainmaker/dev-packages/egov-ui-kit-dev/src/config/forms/specs/PropertyTaxPay/ownerInfo.js
- web/rainmaker/dev-packages/egov-ui-kit-dev/src/config/forms/specs/PropertyTaxPay/ownershipType.js
- web/rainmaker/dev-packages/egov-ui-kit-dev/src/config/forms/specs/PropertyTaxPay/utils/reusableFields.js
RAIN-2703 PT Localization :: English messages are displayed on Old UI if Hindi is selected
> RAIN-2703 PT Localization :: English messages are displayed on Old UI if Hindi is selected

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-molecules-local/DocumentList/index.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-utils/commons.js
RAIN-2703 WNS Localization :: English messages are displayed on Old UI if Hindi is selected
> RAIN-2703 WNS Localization :: English messages are displayed on Old UI if Hindi is selected

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/review-owner.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/applyResource/reviewOwner.js
RAIN-2703 updated localization keys
> RAIN-2703 updated localization keys

- web/dss-dashboard/src/components/Charts/PerformanceChart.js
- web/dss-dashboard/src/components/Charts/TableChart.js
- web/dss-dashboard/src/components/Dashboard/download/filterTable.js
- web/dss-dashboard/src/components/common/UiTable/UiTable.js
- web/dss-dashboard/src/utils/commons.js
- web/rainmaker/packages/citizen/src/modules/App.js
- web/rainmaker/packages/employee/src/modules/App.js
* RAIN-2703 : DSS Localisation Header and card Value fix
* DSS Updated the Table Values with Localisation Prefix
* Modified to Fixed Footers Incase of DSS screen
* DSS Localisation enabled on all missing fields in the table
> RAIN-2703 : DSS Localisation Header and Table values fix (#2442)

- web/rainmaker/dev-packages/egov-ui-framework-core/src/ui-utils/commons.js
RAIN-2767 W&S :: Not able to get the searched result over UI.
> RAIN-2767 W&S :: Not able to get the searched result over UI.

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-atoms-local/LinkAtom/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/footer.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/applyResource/scrutinyDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/summaryResource/scrutinySummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/applyResource/scrutinyDetails.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/oc-bpa/summaryResource/scrutinySummary.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-containers-local/DownloadFileContainer/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-containers-local/FeildInspectionCards/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/BpaDocumentList/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/MultiDocDetailCard/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/NocData/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/NocDetailCard/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/NocDocDetailCard/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/SingleDocDetailCard/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/Table/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-utils/commons.js
RAIN-2766 BPA :: English messages are displayed on Old UI if Hindi is selected
> RAIN-2766 BPA :: English messages are displayed on Old UI if Hindi is selected

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/noc-search.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/egov-bpa/noc.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/CheckList/index.js
- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-molecules-local/UploadCard/index.js
- web/rainmaker/dev-packages/egov-noc-dev/src/ui-config/screens/specs/noc/search.js
- web/rainmaker/dev-packages/egov-noc-dev/src/ui-molecules-local/MultiDocDetailCard/index.js
- web/rainmaker/dev-packages/egov-noc-dev/src/ui-molecules-local/UploadCard/index.js
RAIN-2776 BPA :: English messages are displayed on Old UI if Hindi is selected
> RAIN-2776 BPA :: Fixed few Localisation Header and Label Issues.

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/connection-details.js
RAIN-2770 W&S : Connection holder details repeated in connection details page.
> RAIN-2770 W&S : Connection holder details repeated in connection details page.

- web/dss-dashboard/src/components/common/Card/Card.js
- web/rainmaker/dev-packages/egov-firenoc-dev/src/ui-config/screens/specs/fire-noc/search-preview.js
- web/rainmaker/dev-packages/egov-firenoc-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/packages/employee/src/modules/employee/reports/reportResult.js
RAIN-2785 : Firenoc Sendback to citizen bill search fix incase Application is paid
> RAIN-2785 : Firenoc Sendback to citizen bill search fix incase Application is paid

- web/rainmaker/dev-packages/egov-bpa-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-noc-dev/src/ui-molecules-local/MultiDocDetailCard/index.js
OAP-664 Upload button UI issue in FireNOC step
> OAP-664 Upload button UI issue in FireNOC step

- web/rainmaker/dev-packages/egov-workflow-dev/src/ui-molecules-local/Stepper/index.css
Rain 2610 Auto Escalation: UI Changes
> Rain 2610 Auto Escalation: UI Changes

- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/abg/groupBillResource/functions.js
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/abg/groupBillResource/groupBillSearch.js
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/utils/receiptPdf.js
RAIN-2731 UI-WNS Merge Water and Sewerage connection Bills in Group Bill Section
> RAIN-2731 UI-WNS Merge Water and Sewerage connection Bills in Group Bill Section

- web/rainmaker/dev-packages/egov-ui-kit-dev/src/redux/app/actions.js
RAIN-2610 replced with requestbody
> RAIN-2610 replced with requestbody

- web/rainmaker/dev-packages/egov-tradelicence-dev/src/ui-config/screens/specs/tradelicence/apply.js
- web/rainmaker/dev-packages/egov-tradelicence-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-tradelicence-dev/src/ui-utils/commons.js
RAIN-2601 TL :: Application details are not pre-populated while editing the initiated application
> RAIN-2601 TL :: Application details are not pre-populated while editing the initiated application

- web/rainmaker/dev-packages/egov-common-dev/src/ui-config/screens/specs/egov-common/payResource/footer.js
> Update tenantId fetch method

- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-mutation/mutation-methods.js
- web/rainmaker/dev-packages/egov-ui-framework-core/src/ui-config/screens/specs/utils/index.js
This reverts commit dec2b98676d90d729c14ef6be5d4155176513f62.
> RAIN-2875 : PT Fuzzy search char updated to min 3

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/search-preview.js
RAIN-3068 W&S :: New application changes to modify application after submission.
> RAIN-3068 W&S :: New application changes to modify application after submission.

- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/bills/billSearch.js
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/bills/billSearchResources/billSearchCard.js
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/bills/billSearchResources/function.js
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/bills/billSearchResources/searchResults.js
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/bills/cancelBill.js
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/bills/index.scss
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/bills/viewBill.js
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/bills/viewBillResource/cancelBillDetails.js
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/bills/viewBillResource/footer.js
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/bills/viewBillResource/index.scss
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/bills/viewBillResource/ownerDetails.js
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/bills/viewBillResource/propertyDetails.js
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/bills/viewBillResource/serviceDetails.js
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/bills/viewBillResource/viewBillFooter.js
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-utils/commons.js
- web/rainmaker/dev-packages/egov-ui-kit-dev/src/utils/commons.js
- web/rainmaker/packages/employee/src/ui-config/commonConfig/remote-config-paths/index.js
RAIN-2485 W&S: Current Bill Cancellation
> RAIN-2485 W&S: Current Bill Cancellation

- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/bills/acknowledgement.js
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/bills/acknowledgementResource/acknowledgementUtils.js
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/bills/acknowledgementResource/footers.js
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/bills/acknowledgementResource/index.scss
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/bills/billSearch.js
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/bills/billSearchResources/billSearchCard.js
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/bills/billSearchResources/function.js
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/bills/billSearchResources/searchResults.js
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/bills/cancelBill.js
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/bills/index.scss
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/bills/viewBill.js
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/bills/viewBillResource/cancelBillDetails.js
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/bills/viewBillResource/footer.js
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/bills/viewBillResource/index.scss
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/bills/viewBillResource/ownerDetails.js
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/bills/viewBillResource/propertyDetails.js
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/bills/viewBillResource/serviceDetails.js
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/bills/viewBillResource/viewBillFooter.js
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-utils/commons.js
- web/rainmaker/dev-packages/egov-ui-kit-dev/src/utils/commons.js
- web/rainmaker/packages/employee/src/ui-config/commonConfig/remote-config-paths/index.js
Rain 2485 W&S: Current Bill Cancellation
> Rain 2485 W&S: Current Bill Cancellation

- web/rainmaker/packages/employee/src/modules/employee/reports/index.scss
This reverts commit 034cb53fcceb281bdc7706e430f3eae933d1845c.
> RAIN-3191 : Report buttons Alignment css issue fix

- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/utils/receiptPdf.js
RAIN-3203 W&S :: Combined PDF :: Unrelevant Bills are getting downloaded on clicking merge and download water connection.
> RAIN-3203 W&S :: Combined PDF :: Unrelevant Bills are getting downloaded on clicking merge and download water connection.

- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/connection-details.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/connectionDetailsResource/service-details.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-molecules-local/ActionFooter/index.js
RAIN-3199 W&S :: Cached URL Redirection is there on meter Reading Addition Screen.
> RAIN-3199 W&S :: Cached URL Redirection is there on meter Reading Addition Screen.

- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-common-screens/applyResourceMutation/propertyOwnershipDetails.js
RAIN-3230 Wns :: Property Registry :: Not able to select few of the special applicant category as scroll bar is not there in the dropdown .
> RAIN-3230 Wns :: Property Registry :: Not able to select few of the special applicant category as scroll bar is not there in the dropdown .

- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/bills/viewBillResource/cancelBillDetails.js
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/bills/viewBillResource/viewBillFooter.js
RAIN-3234 Wns :: Bill Cancellation :: Details for the Bill Cancellation Field is diabled.
> RAIN-3234 Wns :: Bill Cancellation :: Details for the Bill Cancellation Field is diabled.

- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/abg/groupBillResource/functions.js
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/abg/groupBillResource/searchResults.js
RAIN-3237 Wns :: Bill Genie :: Not able to download the Bill from group Bills searched result.
> RAIN-3237 Wns :: Bill Genie :: Not able to download the Bill from group Bills searched result.

- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-common-screens/applyResourceMutation/propertyOwnershipDetails.js
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-common-screens/summaryResource/propertyOwnershipSummary.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-utils/commons.js
RAIN-3231 Bill Genie :: Payer Address is coming is NA in the Bill PDF.
> RAIN-3231 Bill Genie :: Payer Address is coming is NA in the Bill PDF.

- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/bills/acknowledgement.js
- web/rainmaker/dev-packages/egov-abg-dev/src/ui-config/screens/specs/bills/viewBill.js
RAIN-3281 Wns :: Bill Cancellation :: Cached Bill Cancellation Success screen is shown when tried to cancel another Bill.
> RAIN-3281 Wns :: Bill Cancellation :: Cached Bill Cancellation Success screen is shown when tried to cancel another Bill.

- web/rainmaker/dev-packages/egov-common-dev/src/ui-config/screens/specs/egov-common/acknowledgement.js
- web/rainmaker/dev-packages/egov-common-dev/src/ui-config/screens/specs/egov-common/download-receipt.js
- web/rainmaker/dev-packages/egov-common-dev/src/ui-config/screens/specs/egov-common/payResource/footer.js
- web/rainmaker/dev-packages/egov-common-dev/src/ui-containers-local/CustomTabContainer/payment-methods.js
- web/rainmaker/dev-packages/egov-common-dev/src/ui-utils/commons.js
- web/rainmaker/dev-packages/egov-firenoc-dev/src/ui-config/screens/specs/fire-noc/applyResource/propertyLocationDetails.js
- web/rainmaker/dev-packages/egov-firenoc-dev/src/ui-utils/commons.js
- web/rainmaker/dev-packages/egov-hrms-dev/src/ui-config/screens/specs/utils/index.js
- web/rainmaker/dev-packages/egov-pt-dev/src/ui-config/screens/specs/pt-mutation/functions.js
- web/rainmaker/dev-packages/egov-ui-kit-dev/src/common/propertyTax/AssessmentList/components/PTInformation/components/AssessmentHistory/index.js
- web/rainmaker/dev-packages/egov-ui-kit-dev/src/common/propertyTax/AssessmentList/components/PTInformation/index.js
- web/rainmaker/dev-packages/egov-ui-kit-dev/src/common/propertyTax/Property/components/OwnerInfo/index.js
- web/rainmaker/dev-packages/egov-ui-kit-dev/src/common/propertyTax/Property/components/PendingAmountDue/index.js
- web/rainmaker/dev-packages/egov-ui-kit-dev/src/common/propertyTax/Property/components/PendingAmountDue/index.scss
- web/rainmaker/dev-packages/egov-ui-kit-dev/src/hocs/withoutAuthorization.js
- web/rainmaker/dev-packages/egov-ui-kit-dev/src/redux/properties/actions.js
- web/rainmaker/dev-packages/egov-ui-kit-dev/src/utils/PTCommon/FormWizardUtils/formUtils.js
- web/rainmaker/dev-packages/egov-ui-kit-dev/src/utils/api.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-config/screens/specs/wns/ImpelExtendedFeature/fields.js
- web/rainmaker/dev-packages/egov-wns-dev/src/ui-utils/commons.js
- web/rainmaker/dev-packages/pgr-citizen-dev/src/Screens/ComplaintDetails/index.js
- web/rainmaker/dev-packages/pgr-employee-dev/src/Screens/ComplaintResolved/components/ComplaintResolvedForm/index.js
- web/rainmaker/packages/citizen/src/modules/citizen/WhatsAppScreen/City/index.js
- web/rainmaker/packages/citizen/src/modules/citizen/WhatsAppScreen/Locality/index.js
Reverts egovernments/frontend#2543
> Revert "Punjab digit v2.2"

- web/rainmaker/dev-packages/egov-tradelicence-dev/src/ui-config/screens/specs/tradelicence/applyResource/footer.js
RAIN-3341 TL :: Old UI :: Locality is displayed in codes on Summary page
> RAIN-3341 TL :: Old UI :: Locality is displayed in codes on Summary page

- web/rainmaker/dev-packages/egov-firenoc-dev/src/ui-atoms-local/AutoSuggest/index.js
- web/rainmaker/dev-packages/egov-firenoc-dev/src/ui-containers-local/AutosuggestContainer/index.js
- web/rainmaker/dev-packages/egov-tradelicence-dev/src/ui-config/screens/specs/tradelicence/applyResource/footer.js
- web/rainmaker/dev-packages/egov-ui-kit-dev/src/common/propertyTax/AssessmentList/components/PTInformation/index.js
- web/rainmaker/packages/employee/src/modules/employee/Erp/EGF/index.js
Master to Develop branch merging
> Master to Develop branch merging

- web/rainmaker/packages/employee/src/modules/employee/Inbox/components/TableData/index.js
RAIN-3349 Auto Escalation ::  Duplicate applications issue fixed
> RAIN-3349 Auto Escalation ::  Duplicate applications issue fixed
